version: "3"
services:
    redis:
        container_name: redis
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
          - 'net1'    
        volumes:
          - 'vol1:/data'  
    web2:
        container_name: web2
        depends_on:
          - 'redis'  
        env_file:
          - '.env'
        build: 
          context: .
          dockerfile: ./Dockerfile
        ports:
            - "5000:5000"
        networks:
          - 'net1'    
        volumes:
          - 'vol1:/app/public'      
networks:
  net1: 
    driver: bridge
volumes: 
  vol1:
    driver: local
    


